<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2017.0.3.363
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Preorder Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Selected',
		'checkbox_unchecked' => 'Unselected',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'akeepwalker@gmail.com',
		'to' => 'akeepwalker@gmail.com'
	),
	'fields' => array(
		'custom_U3014' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Name\' is required.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Email',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Email\' is required.',
				'format' => 'Field \'Email\' has an invalid email address.'
			)
		),
		'custom_U3056' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Home Address',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Home Address\' is required.'
			)
		),
		'custom_U3073' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'City',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'City\' is required.'
			)
		),
		'custom_U3089' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'State',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'State\' is required.'
			)
		),
		'custom_U3105' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Postcode',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Postcode\' is required.'
			)
		),
		'custom_U3137' => array(
			'order' => 1,
			'type' => 'radiogroup',
			'label' => 'Select a package type',
			'required' => true,
			'optionItems' => array(
				'Ecstatic Drinker (Best Value) $44.99',
				'Enthusiastic Drinker $24.99',
				'Happy Drinker'
			),
			'errors' => array(
				'required' => 'Field \'Select a package type\' is required.',
				'format' => 'Field \'Select a package type\' has an invalid value.'
			)
		)
	)
);

process_form($form);
?>
